version: '3'
services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '8086:8086'
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=dbName
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=user  # User for reading data in grafana
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
  grafana:
    image: grafana/grafana:7.3.4
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE=browser
volumes:
    influxdb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './influxdb'
    grafana-data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './grafana-data'
